[0m00:47:58.103987 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3E9825ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3E981BD50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3E989AE10>]}


============================== 00:47:58.108370 | 120d5f58-04f4-4620-a9a4-acb5388b0f69 ==============================
[0m00:47:58.108370 [info ] [MainThread]: Running with dbt=1.10.2
[0m00:47:58.109379 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --profiles-dir .', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:47:58.111371 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\PROJECTS\DBT + DUCKDB + RAG\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:47:58.112371 [debug] [MainThread]: Command `dbt run` failed at 00:47:58.112371 after 0.10 seconds
[0m00:47:58.112371 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3E9825950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3E982D050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3E981B5D0>]}
[0m00:47:58.113819 [debug] [MainThread]: Flushing usage events
[0m00:47:58.869227 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:34:23.866914 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197AA7A52D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197AA7A7210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197AA7A6F90>]}


============================== 01:34:23.872110 | 5aef0fd3-a3d7-4ece-b7e6-8dfec3dcc72f ==============================
[0m01:34:23.872110 [info ] [MainThread]: Running with dbt=1.10.2
[0m01:34:23.874787 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --profiles-dir .', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:34:23.875823 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\PROJECTS\DBT + DUCKDB + RAG\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:34:23.878155 [debug] [MainThread]: Command `dbt run` failed at 01:34:23.878155 after 0.13 seconds
[0m01:34:23.879148 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197AA72CF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197AA79EF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000197AA79F410>]}
[0m01:34:23.879148 [debug] [MainThread]: Flushing usage events
[0m01:34:24.456473 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:34:27.846836 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD6E228FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD7409FD50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD7409EF90>]}


============================== 01:34:27.850837 | 320452b5-f3c4-48a8-965a-f0163147915c ==============================
[0m01:34:27.850837 [info ] [MainThread]: Running with dbt=1.10.2
[0m01:34:27.851837 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run --profiles-dir .', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:34:27.852841 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\PROJECTS\DBT + DUCKDB + RAG\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:34:27.854839 [debug] [MainThread]: Command `dbt run` failed at 01:34:27.853838 after 0.09 seconds
[0m01:34:27.854839 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD7402D010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD7401B590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD7401B410>]}
[0m01:34:27.855837 [debug] [MainThread]: Flushing usage events
[0m01:34:28.412117 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:34:32.950566 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017676DA59D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176769E11D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017676D9FD50>]}


============================== 01:34:32.954563 | e7c30d37-7387-41f3-8e9c-89daa521b92c ==============================
[0m01:34:32.954563 [info ] [MainThread]: Running with dbt=1.10.2
[0m01:34:32.955574 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '.', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --profiles-dir .', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:34:32.956587 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\PROJECTS\DBT + DUCKDB + RAG\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:34:32.957589 [debug] [MainThread]: Command `dbt run` failed at 01:34:32.957589 after 0.09 seconds
[0m01:34:32.958592 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017676D2D2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017676ACE550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017676D1B690>]}
[0m01:34:32.959590 [debug] [MainThread]: Flushing usage events
[0m01:34:33.509258 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:36:49.282063 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028DB69B57D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028DB69B6210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028DB6942010>]}


============================== 19:36:49.292467 | 942b8b27-282e-444f-ab1c-11b4b7707335 ==============================
[0m19:36:49.292467 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:36:49.294613 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\wes\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:36:49.296281 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\wes\Documents\New folder\csv-duckbd-dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:36:49.298318 [debug] [MainThread]: Command `dbt deps` failed at 19:36:49.298318 after 0.20 seconds
[0m19:36:49.300353 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028DB66D6850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028DB69CD650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028DB0757A50>]}
[0m19:36:49.300353 [debug] [MainThread]: Flushing usage events
[0m19:36:50.206985 [debug] [MainThread]: An error was encountered while trying to flush usage events
